#!/bin/bash
# Exporting Environment Variables
#########################################
source ./phpqstat.conf
#########################################

#set -xv

while getopts RMfh:g:u:o:e:s:j:q: OPTION
do
    case $OPTION in
      s) state=$OPTARG
	 stateopt="-s $state"
      ;;

      g) group=$OPTARG
         groupopt="-u $group*"
	 ;;
	 
      u) user=$OPTARG
         if [ $user == "all" ]; then
	  user="*"
	  useropt="-u"
	 else
          group=$(id -gn $user)
          useropt="-u"
	 fi
	 ;;
      o) out=$OPTARG
	 ;;
      e) error=$OPTARG
         erroropt="-explain $error"
	 ;;
      j) jobid=$OPTARG
         jobidopt="-j $jobid"
	 ;;
      q) queue=$OPTARG
	 queueopt="-q $queue"
      ;;
	 
      R) sw_R="-g c" #queues status
	 ;;
	 
      M) sw_M=1
	 ;;
	 
      f) sw_f="-f"
	 ;;

      h) help $tipus_usuari ;;

      ?) echo "Opcio invalida."; exit ;;
    esac
done


qstat -xml -ext -r $stateopt $queueopt $sw_R $sw_f $groupopt $useropt "$user" $erroropt $jobidopt > $out

exit
