#!/bin/bash
# Modify your SGE_ROOT
#########################################
export SGE_ROOT=/sge
source $SGE_ROOT/default/common/settings.sh
#########################################
qhost -xml > $1
